Kiddywee/Controllers/ClassController.cs
using Kiddywee.DAL.Enum;
using Kiddywee.DAL.Interfaces;
using Kiddywee.DAL.Models;
using Kiddywee.DAL.ViewModels.ClassesViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kiddywee.Controllers
{
    [Authorize]
    public class ClassController : BaseController
    {
        public ClassController(IUnitOfWork unitOfWork, ICompositeViewEngine viewEngine) : base(unitOfWork, viewEngine)
        {
            _unitOfWork = unitOfWork;
        }

        public string SelectClass(Guid classId)
        {
            _classId = classId;
            return _classId.ToString();
        }

        public IActionResult Create(string id)
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(ClassCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var @class = Class.Create(model, _userId);
                await _unitOfWork.Classes.Insert(@class);
                await _unitOfWork.SaveAsync();
                return Redirect(Request.Headers["Referer"].ToString());
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var @class = await _unitOfWork.Classes.GetOneAsync(x => x.IsActive && x.Id == id);
            var allClassesExeptSelected = await _unitOfWork.Classes.GetAsync(x => x.IsActive && x.Id != id);
            var model = Class.Init(@class, allClassesExeptSelected);
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(ClassEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var @class = await _unitOfWork.Classes.GetOneAsync(x => x.Id == model.ClassId);
                if (model.IsMove && model.MoveClassId.HasValue)
                {
                    //Удаление классов

                    //if (model.IsActive)
                    //{
                    //    @class.IsActive = false;
                    //}
                    var personToClasses = await _unitOfWork.PersonToClasses.GetAsync(x => x.IsActive && x.ClassId == model.ClassId);
                    personToClasses.ForEach(x => x.IsActive = false);
                    var newPersonToClasses = new List<PersonToClass>();
                    foreach (var item in personToClasses)
                    {
                        newPersonToClasses.Add(PersonToClass.Create(item.PersonId, model.MoveClassId.Value, _userId));
                    }
                    _unitOfWork.PersonToClasses.UpdateRange(personToClasses);
                    await _unitOfWork.PersonToClasses.InsertRange(newPersonToClasses);
                    var result = await _unitOfWork.SaveAsync();

                }
                else
                {
                    @class.Update(model);
                    _unitOfWork.Classes.Update(@class);
                    await _unitOfWork.SaveAsync();
                }
                return Redirect(Request.Headers["Referer"].ToString());
            }
            return View(model);
        }


        public async Task<JsonResult> InitClasses()
        {
            var result = new List<ClassViewModel>();
            var startDate = new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, DateTime.UtcNow.Day);
            var endDate = new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, DateTime.UtcNow.Day, 23, 59, 59);

            var classes = await _unitOfWork.Classes.GetAsync(p => p.IsActive && p.OrganizationId == _organizationId.Value);
            var attendancesForToday = _unitOfWork.Attendances.Get(x => x.IsActive
                                                                        && x.InDate >= startDate
                                                                        && x.InDate <= endDate
                                                                        && x.OrganizationId == _organizationId.Value);

            var persons = _unitOfWork.People.Get(p => p.OrganizationId == _organizationId,
                include: p => p.Include(x => x.StaffInfo).Include(x => x.ChildInfo).Include(p => p.PersonToClasses));

            var staffInOrganization = persons.Where(x => x.StaffInfo != null);
            var childrenInOrganization = persons.Where(x => x.ChildInfo != null);
            result = Class.Init(classes, attendancesForToday, persons);            

            var jsonresult = result.Select(p => new
            {
                ClassId = p.ClassId.ToString(),
                StaffIn = p.StaffIn,
                StaffTotal = p.StaffTotal,
                ChildrenIn = p.ChildrenIn,
                ChildrenTotal = p.ChildrenTotal
            }).ToList();

            var attendanceToSchool = attendancesForToday.Where(x => x.ClassId == null);
            int childrenInsideSchool = 0;
            int staffInsideSchool = 0;

            foreach(var p in persons)
            {
                var attendanceForPerson = attendanceToSchool.FirstOrDefault(x => x.PersonId == p.Id);
                if(attendanceForPerson != null)
                {
                    if(attendanceForPerson.OutDate.HasValue == false)
                    {
                        if(p.ChildInfo != null)
                        {
                            ++childrenInsideSchool;
                        }
                        if(p.StaffInfo != null)
                        {
                            ++staffInsideSchool;
                        }
                    }
                }
            }

            jsonresult.Add(new
            {
                ClassId = "0",
                StaffIn = staffInsideSchool,
                StaffTotal = staffInOrganization.Count(),
                ChildrenIn = childrenInsideSchool,
                ChildrenTotal = childrenInOrganization.Count()
            }); 
            return Json(jsonresult.OrderBy(p => p.ClassId).ToList());
        }
    }
}

Kiddywee/Controllers/FileController.cs
using Kiddywee.BLL.Core;
using Kiddywee.DAL.Interfaces;
using Kiddywee.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace Kiddywee.Controllers
{
    [Authorize]
    public class FileController : BaseController
    {
        public FileController(IUnitOfWork unitOfWork, ICompositeViewEngine viewEngine) : base(unitOfWork, viewEngine)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpPost]
        public async Task<JsonResult>  UploadProfileImage(Guid personId, IFormFile file)
        {
            var person = await _unitOfWork.People.GetOneAsync(x => x.Id == personId);
            person.ProfileImage = await file.GetBytes();
            _unitOfWork.People.Update(person);
            await _unitOfWork.SaveAsync();
            var base64String = Convert.ToBase64String(person.ProfileImage);
            string resultString = $"data:{file.ContentType};base64,{base64String}";
            return Json(new JsonMessage { Color = "#ff6849", Message = "Logo uploaded", Header = "Success", Icon = "success", AdditionalData = new {src=resultString } });

        }
        public ActionResult GetProfileImage(Guid personId)
        {
            byte[] profileImageData = _unitOfWork.People.GetOne(x => x.Id == personId)?.ProfileImage;
            //для дефолтной картинки
            if(profileImageData == null)            
            {
                profileImageData = Convert.FromBase64String(Constants.DEFAULT_USER_LOGO);                
            }
            return File(profileImageData, "image/png");
        }

        
        public async Task<IActionResult> DownloadFile(Guid fileId)
        {
            DAL.Models.FileInfo file = await _unitOfWork.FileInfos.GetOneAsync(x => x.Id == fileId);
            return File(file.Data, file.Extention, file.Name);
        }

        public async Task<JsonResult> DeleteFile(Guid fileId)
        {
            DAL.Models.FileInfo file = await _unitOfWork.FileInfos.GetOneAsync(x => x.Id == fileId);
            file.IsActive = false;
            _unitOfWork.FileInfos.Update(file);
            var result = await _unitOfWork.SaveFileAsync();
            return Json(new JsonMessage { Color = "#ff6849", Message = "File deleted", Header = "Success", Icon = "success", AdditionalData  = file });

        }


        public async Task<JsonResult> UploadMedicalFile(Guid personId, IFormFile file)
        {
            var medicalInfo = DAL.Models.FileInfo.Create(file, _userId, DAL.Enum.EnumFileType.MedicalInfo, personId);
            await _unitOfWork.FileInfos.Insert(medicalInfo);
            var result = await _unitOfWork.SaveFileAsync();
            if(result.Succeeded)
            {
                return Json(new JsonMessage { Color = "#ff6849", Message = "File uploded", Header = "Success", Icon = "success", AdditionalData = medicalInfo });

            }
            return Json(new JsonMessage { Color = "#ff6849", Message = "File error", Header = "Error", Icon = "error", AdditionalData = medicalInfo });

        }
    }
}

Kiddywee/Views/Shared/_PartialClasses.cshtml
@{
    var items = (List<ClassViewModel>)ViewBag.Classes;
    if(ViewBag.Page == "DailyReports")
    {
        items = items.Where(x => x.ClassId != "0").ToList();
    }
}



<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <div class="row ml-lg-0">
            <div class="align-self-center"><input class="typeahead form-control" id="search-class" type="text" placeholder="Search class" /></div>
            <div class="align-self-center m-l-10 "><i class="fa-1x fas fa-ban " id="search-class-reset" style="color:red;"></i></div> 
        </div>        
    </div>
    <div class="col-md-7 align-self-center text-right d-inline d-md-block">
        <button type="button" class="btn btn-info add-class" data-url="@Url.Action("Create", "Class")">
            <i class="fa fa-plus-circle"></i> Add class
        </button>
    </div>
</div>


<div class="owl-carousel owl-theme">
    @if (items.Any())
    {
        foreach (var item in items)
        {
            <div class="item el-element-overlay class-box" data-name="@item.ClassName" data-classId="@item.ClassId" id="class-id-@item.ClassId">
                <div class="social-widget el-card-item">
                    <div class="el-overlay-1">
                        <div class="soc-header @item.BackgroundColorCss " title="@item.ClassName">@item.ShortClassName</div>
                        <div class="soc-content">
                            <div class="col-6 b-r">
                                <h3 class="font-medium kids-in" id="kids-in-@item.ClassId">@item.ChildrenIn/@item.ChildrenTotal</h3>
                                <h5 class="text-muted">kids in</h5>
                            </div>
                            <div class="col-6">
                                <h3 class="font-medium staff-in" id="staff-in-@item.ClassId">@item.StaffIn/@item.StaffTotal</h3>
                                <h5 class="text-muted">staff in</h5>
                            </div>
                        </div>
                        <div class="el-overlay">
                            <ul class="el-info">
                                <li><a class="btn default btn-outline class-select" data-classId="@item.ClassId" data-url="@Url.Action("Index", "Person", new {classId = item.ClassId})"><i class="sl-icon-magnifier"></i></a></li>
                                <li><a class="btn default btn-outline class-edit" data-url="@Url.Action("Edit", "Class", new {id = item.ClassId})"><i class="sl-icon-pencil"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <div class="text-center">
            <h1 class="display-4">No classes</h1>
        </div>
    }
</div>

Kiddywee/Views/Shared/_PartialCss.cshtml
<link href="@Url.Content("assets/node_modules/bootstrap/css/bootstrap.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/select2/dist/css/select2.min.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/morrisjs/morris.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/c3-master/c3.min.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/toast-master/css/jquery.toast.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("css/style.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("css/colors/blue-dark.css")" id="theme" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/owl.carousel/owl.carousel.min.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/owl.carousel/owl.theme.default.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/Magnific-Popup-master/dist/magnific-popup.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/datatables.net-bs4/css/responsive.dataTables.min.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/dropzone-master/dist/dropzone.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/calendar/dist/fullcalendar.css")" rel="stylesheet" asp-append-version="true">
<link href="@Url.Content("assets/node_modules/clockpicker/dist/jquery-clockpicker.min.css")" rel="stylesheet" asp-append-version="true">
@*<link href="@Url.Content("css/pages/table-pages.css")" rel="stylesheet" asp-append-version="true">*@ 

Kiddywee/Views/Shared/_PartialJavaScript.cshtml
<script src="@Url.Content("assets/node_modules/jquery/jquery.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/bootstrap/js/popper.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/bootstrap/js/bootstrap.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/select2/dist/js/select2.full.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/ps/perfect-scrollbar.jquery.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/raphael/raphael.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/morrisjs/morris.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/c3-master/c3.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/toast-master/js/jquery.toast.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/styleswitcher/jQuery.style.switcher.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/owl.carousel/owl.carousel.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/sticky-kit-master/dist/sticky-kit.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/sparkline/jquery.sparkline.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/Magnific-Popup-master/dist/jquery.magnific-popup.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/Magnific-Popup-master/dist/jquery.magnific-popup-init.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/datatables.net/js/jquery.dataTables.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/datatables.net-bs4/js/dataTables.responsive.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/date-paginator/moment.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/calendar/jquery-ui.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/date-paginator/bootstrap-datepaginator.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/dropzone-master/dist/dropzone.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/typeahead.js-master/dist/typeahead.bundle.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/moment/moment.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/calendar/dist/fullcalendar.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("assets/node_modules/clockpicker/dist/jquery-clockpicker.min.js")" asp-append-version="true"></script>
<script src="@Url.Content("js/waves.js")" asp-append-version="true"></script>
<script src="@Url.Content("js/sidebarmenu.js")" asp-append-version="true"></script>
<script src="@Url.Content("js/custom.min.js")" asp-append-version="true"></script>

<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>

Kiddywee/Views/Shared/_PartialNavigation.cshtml
<aside class="left-sidebar">
    <div class="scroll-sidebar">
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                @*<li class="nav-devider"></li>
        <li class="nav-small-cap">PERSONAL</li>*@
                <li>
                    <a class="has-arrow waves-effect waves-dark" asp-action="Index" asp-controller="Home"><i class="icon-Checked-User"></i><span>Attendance</span></a>
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" asp-action="Index" asp-controller="Education"><i class="icon-Receipt-4"></i><span>Lesson plans</span></a>
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" asp-action="Index" asp-controller="DailyReports"><i class="icon-doc"></i><span>Daily Reports</span></a>
                </li>
                @*<li>
            <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="icon-Double-Circle"></i><span class="hide-menu">Apps</span></a>
            <ul aria-expanded="false" class="collapse">
                <li><a href="app-calendar.html">Calendar</a></li>
                <li>
                    <a class="has-arrow" href="#" aria-expanded="false">Inbox</a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="app-email.html">Mailbox</a></li>
                        <li><a href="app-email-detail.html">Mailbox Detail</a></li>
                        <li><a href="app-compose.html">Compose Mail</a></li>
                    </ul>
                </li>
                <li><a href="app-chat.html">Chat app</a></li>
                <li><a href="app-ticket.html">Support Ticket</a></li>
                <li><a href="app-contact.html">Contact / Employee</a></li>
                <li><a href="app-contact2.html">Contact Grid</a></li>
                <li><a href="app-contact-detail.html">Contact Detail</a></li>
            </ul>
        </li>*@
            </ul>
        </nav>
    </div>
</aside>

Kiddywee/Views/Shared/_PartialNotifications.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="icon-Bell"></i>
        <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
    </a>
    <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown">
        <ul>
            <li>
                <div class="drop-title">Notifications</div>
            </li>
            <li>
                <div class="message-center">
                    <!-- Message -->
                    <a href="#">
                        <div class="btn btn-danger btn-circle"><i class="fa fa-link"></i></div>
                        <div class="mail-contnet">
                            <h5>Luanch Admin</h5> <span class="mail-desc">Just see the my new admin!</span> <span class="time">9:30 AM</span>
                        </div>
                    </a>
                    <!-- Message -->
                    <a href="#">
                        <div class="btn btn-success btn-circle"><i class="ti-calendar"></i></div>
                        <div class="mail-contnet">
                            <h5>Event today</h5> <span class="mail-desc">Just a reminder that you have event</span> <span class="time">9:10 AM</span>
                        </div>
                    </a>
                    <!-- Message -->
                    <a href="#">
                        <div class="btn btn-info btn-circle"><i class="ti-settings"></i></div>
                        <div class="mail-contnet">
                            <h5>Settings</h5> <span class="mail-desc">You can customize this template as you want</span> <span class="time">9:08 AM</span>
                        </div>
                    </a>
                    <!-- Message -->
                    <a href="#">
                        <div class="btn btn-primary btn-circle"><i class="ti-user"></i></div>
                        <div class="mail-contnet">
                            <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span>
                        </div>
                    </a>
                </div>
            </li>
            <li>
                <a class="nav-link text-center" href="javascript:void(0);"> <strong>Check all notifications</strong> <i class="fa fa-angle-right"></i> </a>
            </li>
        </ul>
    </div>
</li>                        

Kiddywee/Views/Shared/_PartialUserCard.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="@Url.Action("GetProfileImage", "File", new { personId = ViewBag.User.PersonId})" alt="user" class="profile-pic" /></a>
    <div class="dropdown-menu dropdown-menu-right animated flipInY">
        <ul class="dropdown-user">
            <li>
                <div class="dw-user-box">
                    <div class="u-img"><img src="@Url.Action("GetProfileImage", "File", new { personId = ViewBag.User.PersonId})" alt="user"></div>
                    <div class="u-text">
                        <h4>@ViewBag.User.UserFullName</h4>
                    </div>
                </div>
            </li>
            <li role="separator" class="divider"></li>
            <li><a id="user-profile" data-url="@Url.Action("EditUserProfile","Person", new { personId = ViewBag.User.PersonId} )"><i class="ti-user"></i> My Profile</a></li>                    
            <li role="separator" class="divider"></li>
            <li><a asp-action="Logout" asp-controller="Account"><i class="fa fa-power-off"></i> Logout</a></li>
        </ul>
    </div>
</li>