Kiddywee/Controllers/FileController.cs
using Kiddywee.BLL.Core;
using Kiddywee.DAL.Interfaces;
using Kiddywee.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace Kiddywee.Controllers
{
    [Authorize]
    public class FileController : BaseController
    {
        public FileController(IUnitOfWork unitOfWork, ICompositeViewEngine viewEngine) : base(unitOfWork, viewEngine)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpPost]
        public async Task<JsonResult>  UploadProfileImage(Guid personId, IFormFile file)
        {
            var person = await _unitOfWork.People.GetOneAsync(x => x.Id == personId);
            person.ProfileImage = await file.GetBytes();
            _unitOfWork.People.Update(person);
            await _unitOfWork.SaveAsync();
            var base64String = Convert.ToBase64String(person.ProfileImage);
            string resultString = $"data:{file.ContentType};base64,{base64String}";
            return Json(new JsonMessage { Color = "#ff6849", Message = "Logo uploaded", Header = "Success", Icon = "success", AdditionalData = new {src=resultString } });

        }
        public ActionResult GetProfileImage(Guid personId)
        {
            byte[] profileImageData = _unitOfWork.People.GetOne(x => x.Id == personId)?.ProfileImage;
            //для дефолтной картинки
            if(profileImageData == null)            
            {
                profileImageData = Convert.FromBase64String(Constants.DEFAULT_USER_LOGO);                
            }
            return File(profileImageData, "image/png");
        }

        
        public async Task<IActionResult> DownloadFile(Guid fileId)
        {
            DAL.Models.FileInfo file = await _unitOfWork.FileInfos.GetOneAsync(x => x.Id == fileId);
            return File(file.Data, file.Extention, file.Name);
        }

        public async Task<JsonResult> DeleteFile(Guid fileId)
        {
            DAL.Models.FileInfo file = await _unitOfWork.FileInfos.GetOneAsync(x => x.Id == fileId);
            file.IsActive = false;
            _unitOfWork.FileInfos.Update(file);
            var result = await _unitOfWork.SaveFileAsync();
            return Json(new JsonMessage { Color = "#ff6849", Message = "File deleted", Header = "Success", Icon = "success", AdditionalData  = file });

        }


        public async Task<JsonResult> UploadMedicalFile(Guid personId, IFormFile file)
        {
            var medicalInfo = DAL.Models.FileInfo.Create(file, _userId, DAL.Enum.EnumFileType.MedicalInfo, personId);
            await _unitOfWork.FileInfos.Insert(medicalInfo);
            var result = await _unitOfWork.SaveFileAsync();
            if(result.Succeeded)
            {
                return Json(new JsonMessage { Color = "#ff6849", Message = "File uploded", Header = "Success", Icon = "success", AdditionalData = medicalInfo });

            }
            return Json(new JsonMessage { Color = "#ff6849", Message = "File error", Header = "Error", Icon = "error", AdditionalData = medicalInfo });

        }
    }
}

Kiddywee/Controllers/PersonController.cs
using Kiddywee.BLL.Core;
using Kiddywee.DAL.Interfaces;
using Kiddywee.DAL.Models;
using Kiddywee.DAL.ViewModels.PersonViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kiddywee.Controllers
{
    [Authorize]

    public class PersonController : BaseController
    {
        private ICompositeViewEngine _viewEngine;

        public PersonController(IUnitOfWork unitOfWork, ICompositeViewEngine viewEngine) : base(unitOfWork, viewEngine)
        {
            _unitOfWork = unitOfWork;
            _viewEngine = viewEngine;
        }

        public async Task<IActionResult> Index(Guid? classId)
        {
            var people = new List<Person>();
            if (!classId.HasValue)
            {
                people = await _unitOfWork.People
                    .GetAsync(p => p.OrganizationId == _organizationId && p.IsActive,
                    include: p => p.Include(x => x.StaffInfo)
                                   .Include(x => x.ChildInfo)
                                   .Include(x => x.PersonToClasses)
                                   .Include(x => x.Attendances));
            }
            else
            {
                people = await _unitOfWork.People.GetAsync(p => p.OrganizationId == _organizationId && p.IsActive
                    && p.PersonToClasses.Any(x => x.ClassId == classId.Value && x.IsActive),
                    include: p => p.Include(x => x.PersonToClasses)
                                   .Include(x => x.StaffInfo)
                                   .Include(x => x.ChildInfo)
                                   .Include(x => x.Attendances));
            }


            var model = Person.Init(people, classId);
            return View(model);
        }

        public async Task<IActionResult> ChildrenForDailyReport(Guid? classId)
        {
            var people = new List<Person>();

            if (!classId.HasValue)
            {
                people = await _unitOfWork.People
                    .GetAsync(p => p.OrganizationId == _organizationId && p.IsActive && p.ChildInfo != null,
                    include: p => p.Include(x => x.ChildInfo)
                                   .Include(x => x.PersonToClasses)
                                   .Include(x => x.Attendances));
            }
            else
            {
                people = await _unitOfWork.People.GetAsync(p => p.OrganizationId == _organizationId && p.ChildInfo != null
                    && p.PersonToClasses.Any(x => x.ClassId == classId.Value && x.IsActive),
                    include: p => p.Include(x => x.PersonToClasses)                                   
                                   .Include(x => x.ChildInfo)
                                   .Include(x => x.Attendances));
            }
            List<ChildDailyReportViewModel> model = Person.InitDailyReport(people, classId);

            return View(model);
        }

        #region Create
        [HttpGet]
        public async Task<IActionResult> CreateStaff()
        {
            var classes = await _unitOfWork.Classes.GetAsync(x => x.OrganizationId == _organizationId);
            var organizations = await _unitOfWork.Organizations.GetAsync();
            StaffCreateViewModel model = new StaffCreateViewModel() { Classes = classes, Organizations = organizations };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateStaff(StaffCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var person = Person.Create(model, _organizationId.Value);
                await _unitOfWork.People.Insert(person);
                var personResult = await _unitOfWork.SaveAsync();
                if (personResult.Succeeded)
                {
                    if (model.Files.Any())
                    {
                        foreach (var f in model.Files)
                        {
                            var medicalInfo = FileInfo.Create(f, _userId, DAL.Enum.EnumFileType.MedicalInfo, person.Id);
                            await _unitOfWork.FileInfos.Insert(medicalInfo);
                        }
                        await _unitOfWork.SaveFileAsync();
                    }


                    var staffInfo = StaffInfo.Create(model, _userId);
                    staffInfo.OrganizationId = _organizationId.Value;
                    await _unitOfWork.StaffInfos.Insert(staffInfo);
                    var staffInfoResult = await _unitOfWork.SaveAsync();
                    if (staffInfoResult.Succeeded)
                    {
                        person.StaffInfoId = staffInfo.Id;
                        foreach (var item in model.ClassId)
                        {
                            var personToClass = PersonToClass.Create(person.Id, item, _userId);
                            await _unitOfWork.PersonToClasses.Insert(personToClass);
                        }
                        await _unitOfWork.SaveAsync();
                    }
                }

                return Redirect(Request.Headers["Referer"].ToString());
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> CreateChild()
        {
            var classes = await _unitOfWork.Classes.GetAsync(x => x.OrganizationId == _organizationId);
            ChildCreateViewModel model = new ChildCreateViewModel() { Classes = classes };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateChild(ChildCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var person = Person.Create(model, _organizationId.Value);
                await _unitOfWork.People.Insert(person);
                var personResult = await _unitOfWork.SaveAsync();
                if (personResult.Succeeded)
                {
                    if (model.Files.Any())
                    {
                        foreach (var f in model.Files)
                        {
                            var medicalInfo = FileInfo.Create(f, _userId, DAL.Enum.EnumFileType.MedicalInfo, person.Id);
                            await _unitOfWork.FileInfos.Insert(medicalInfo);
                        }
                        await _unitOfWork.SaveFileAsync();
                    }

                    var childInfo = ChildInfo.Create(model, _userId);
                    await _unitOfWork.ChildInfos.Insert(childInfo);

                    var childResult = await _unitOfWork.SaveAsync();
                    if (childResult.Succeeded)
                    {
                        person.ChildInfoId = childInfo.Id;
                        foreach (var item in model.ClassId)
                        {
                            var personToClass = PersonToClass.Create(person.Id, item, _userId);
                            await _unitOfWork.PersonToClasses.Insert(personToClass);
                        }

                        await _unitOfWork.SaveAsync();
                    }
                }

                return Redirect(Request.Headers["Referer"].ToString());
            }
            return View(model);
        }
        #endregion

        #region Edit
        [HttpGet]
        public async Task<IActionResult> EditStaff(Guid personId)
        {
            var person = await _unitOfWork.People.GetOneAsync(x => x.Id == personId,
                                                                   include: p => p.Include(w => w.StaffInfo));

            var model = StaffInfo.Init(person);
            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> EditStaffGeneralInformation(StaffEditGeneralViewModel model)
        {
            if (ModelState.IsValid)
            {
                var person = await _unitOfWork.People.GetOneAsync(x => x.Id == model.PersonId,
                                                                   include: p => p.Include(w => w.StaffInfo));

                person.Update(model);

                _unitOfWork.People.Update(person);
                var result = await _unitOfWork.SaveAsync();

                return Json(new JsonMessage { Color = "#ff6849", Message = "Person saved", Header = "Success", Icon = "success", AdditionalData = model });

            }
            return Json(new JsonMessage { Color = "#ff6849", Message = "Error", Header = "Error", Icon = "error", AdditionalData = model });
        }

        [HttpGet]
        public async Task<IActionResult> EditStaffOtherInformation(Guid personId)
        {
            var person = await _unitOfWork.People.GetOneAsync(x => x.Id == personId,
                                                                   include: p => p.Include(w => w.StaffInfo).Include(x => x.PersonToClasses));
            var classes = await _unitOfWork.Classes.GetAsync(x => x.OrganizationId == _organizationId && x.IsActive);

            var model = StaffInfo.Init(person, classes);
            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> EditStaffOtherInformation(StaffEditOtherViewModel model)
        {
            if (ModelState.IsValid)
            {

                var person = await _unitOfWork.People.GetOneAsync(x => x.Id == model.PersonId,
                                                                   include: p => p.Include(w => w.StaffInfo).Include(x => x.PersonToClasses));
                var classes = await _unitOfWork.Classes.GetAsync(x => x.OrganizationId == _organizationId && x.IsActive);


                person.Update(model);

                _unitOfWork.People.Update(person);

Kiddywee/Views/Person/Create.cshtml
@model PersonCreateViewModel
@{
    Layout = null;
}
<div class="modal-header">
    <h4 class="modal-title" id="myLargeModalLabel">Create New Class</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="javascipt: window.location.reload()">×</button>
</div>
<div class="modal-body">
    <form class="form-material" id="SavePerson" asp-action="Create" asp-controller="Person" method="post">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Firstname <span class="help"></span></label>
                    <input type="text" asp-for="FirstName" class="form-control form-control-line" placeholder="Enter firstname...">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Lastname<span class="help"></span></label>
                    <input type="text" asp-for="LastName" class="form-control form-control-line" placeholder="Enter lastname">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label>Address<span class="help"></span></label>
            <input type="text" asp-for="Address" class="form-control form-control-line" placeholder="Enter address">
        </div>
        <div class="form-group">
            <label>Date Of Birth<span class="help"></span></label>
            <input type="date" asp-for="DateOfBirth" class="form-control form-control-line" placeholder="Enter date">
        </div>
        <div class="form-group">
            <label>Next medical<span class="help"></span></label>
            <input type="date" asp-for="NextMedical" class="form-control form-control-line" placeholder="Enter date">
        </div>
        <div class="form-group">
            <label>Weekly schedule<span class="help"></span></label> <br />
            @foreach (EnumWeeklyScheduleType item in Enum.GetValues(typeof(EnumWeeklyScheduleType)))
            {
                <input name="WeaklySchedule" type="checkbox" value="@item" /> @item
                <text>&nbsp; &nbsp; &nbsp;</text>
            }
        </div>
        <div class="form-group">
            <label>Daily schedule<span class="help"></span></label> <br />
            @foreach (EnumDailyScheduleType item in Enum.GetValues(typeof(EnumDailyScheduleType)))
            {
                <input name="DailySchedule" type="checkbox" value="@item" /> @item
                <text>&nbsp; &nbsp;</text>
            }
        </div>
        <div class="form-group">
            <label for="example-email">Pipeline Type<span class="help"></span></label>
            <select class="form-control " asp-for="PipeLineType" asp-items="Html.GetEnumSelectList<EnumPipeLineType>()"></select>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger waves-effect " data-dismiss="modal" onclick="javascipt: window.location.reload()">Close</button>
    <button type="submit" class="btn btn-info waves-effect" form="SavePerson">Save</button>
</div>

Kiddywee/Views/Person/EditChildMedicalInformation.cshtml
@model ChildEditMedicalViewModel
@{
    Layout = null;
}
<div class="card-body">
    <div class="form-horizontal " id="SaveChildMedical">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Next medical</label>
                    <input type="date" asp-for="NextMedical" class="form-control form-control-line" placeholder="Enter date">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Allergies</label>
                    <input type="checkbox" asp-for="Allergies">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Allergies notes</label>
                    <input type="text" asp-for="AllergiesNotes" class="form-control form-control-line">
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="PersonId" />
        <div class="text-right">
            <button id="save-person-medical" class="btn btn-info waves-effect">Save</button>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $(function () {
            $("#save-person-medical").click(function (e) {
                if ($('[name="Allergies"]:checked').length > 0) {
                    $('[name="Allergies"]:hidden').val(true);
                } else {
                    $('[name="Allergies"]:hidden').val(false);
                }
                var valdata = {};
                $('#SaveChildMedical').find('input').each(function () {
                    valdata[this.name] = $(this).val();
                });
                $.ajax({
                    url: "/Person/EditChildMedicalInformation",
                    type: "POST",
                    dataType: 'json',
                    data: valdata
                }).done(function (response) {
                    $.toast({
                        heading: response.header,
                        text: response.message,
                        position: 'bottom-right',
                        loaderBg: response.color,
                        icon: response.icon,
                        hideAfter: 10000
                    });
                });
            });
        })
    });
</script>

Kiddywee/Views/Person/EditStaff.cshtml
@model StaffEditGeneralViewModel
@{
    Layout = null;
}
<div class="modal-header">
    <h4 class="modal-title" id="myLargeModalLabel">Edit Staff</h4>
    <button type="button" class="close close-modal" data-dismiss="modal" aria-hidden="true" >×</button>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-lg-4 col-xlg-3 col-md-5">
            <div class="card">
                <div class="card-body">
                    <center class="m-t-30">
                        <div class="el-element-overlay">
                            <div class="el-card-item">
                                <div class="el-overlay-1 img-circle " style="width:150px; height:150px">
                                    <img id="image-profile" src="@Url.Action("GetProfileImage", "File", new { personId = Model.PersonId})" />
                                    <div class="el-overlay">
                                        <ul class="el-info">
                                            <li><a class="btn default btn-outline" id="upload-logo"><i class="sl-icon-cloud-upload"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h4 class="card-title m-t-10" id="person-full-name">@Model.FullName</h4>
                        <input id="file-input" type="file" name="profileLogo" accept="image/*" style="display:none" />
                    </center>
                </div>
                <div>
                    <hr>
                </div>
                <div class="card-body">
                    @*<small class="text-muted">Role</small>
                    <h5 id="person-address">%TODO%</h5>*@
                    <small class="text-muted p-t-30 db">Date Of Birth</small>
                    <h5 id="person-date">@Model.NormalizedDateOfBirth</h5>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-xlg-9 col-md-7">
            <div class="card">
                <ul class="nav nav-tabs profile-tab" role="tablist">
                    <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#profile" role="tab">General</a> </li>
                    <li class="nav-item"> <a class="nav-link staff-other-info" data-url="@Url.Action("EditStaffOtherInformation", "Person", new { personId = Model.PersonId})" data-toggle="tab" href="#other" role="tab">Other</a> </li>
                    <li class="nav-item"> <a class="nav-link staff-file-info" data-url="@Url.Action("EditStaffFileInformation", "Person", new { personId = Model.PersonId})" data-toggle="tab" href="#file" role="tab">Files</a> </li>
                    @*<li class="nav-item"> <a class="nav-link staff-contact-info" data-url="@Url.Action("EditStaffContactInformation", "Person", new { personId = Model.PersonId})" data-toggle="tab" href="#contact" role="tab">Contacts</a> </li>*@
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="profile" role="tabpanel">
                        <div class="card-body">
                            <div class="form-horizontal form-material" id="SavePerson">
                                <div class="form-group">
                                    <label class="col-md-12">Firstname</label>
                                    <div class="col-md-12">
                                        <input type="text" asp-for="FirstName" placeholder="Enter firstname..." class="form-control form-control-line">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Lastname</label>
                                    <div class="col-md-12">
                                        <input type="text" asp-for="LastName" placeholder="Enter lastname..." class="form-control form-control-line">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Date of Birth</label>
                                    <div class="col-md-12">
                                        <input type="date" asp-for="DateOfBirth" class="form-control form-control-line" placeholder="Enter date">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <label class="">Phone number</label>
                                        <div class="col-md-12">
                                            <input type="text" asp-for="PhoneNumber" class="form-control form-control-line" placeholder="Enter phone number">
                                        </div>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <label class="">Phone number digital pin</label>
                                        <div class="col-md-12">
                                            <input type="text" asp-for="PhoneNumberDigitPin" class="form-control form-control-line" placeholder="Enter phone number pin">
                                        </div>
                                    </div>
                                </div>
                                
                                <input type="hidden" asp-for="PersonId" />
                                <div class="text-right">
                                    <button id="save-person-submit" class="btn btn-info waves-effect">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="other" role="tabpanel">
                        <div class="card-body">
                            <div class="d-flex justify-content-center">
                                <div class="spinner-border" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </div>
                        </div>
                    </div>                    
                    <div class="tab-pane" id="file" role="tabpanel">
                        <div class="card-body">
                            <div class="d-flex justify-content-center">
                                <div class="spinner-border" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    @*<div class="tab-pane" id="contact" role="tabpanel">
                        <div class="card-body">
                            <div class="d-flex justify-content-center">
                                <div class="spinner-border" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </div>
                        </div>
                    </div>*@
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger waves-effect close-modal" data-dismiss="modal" >Close</button>
</div>
<script>
    $(document).ready(function () {

        $(document).on("click", ".staff-other-info", function () {
            var url = $(this).data("url");
            $.get(url, function (data) {
                $("#other").html(data);
            })
        });        

        $(document).on("click", ".staff-file-info", function () {
            var url = $(this).data("url");
            $.get(url, function (data) {
                $("#file").html(data);
            })
        });

        //$(document).on("click", ".staff-contact-info", function () {
        //    var url = $(this).data("url");
        //    $.get(url, function (data) {
        //        $("#contact").html(data);
        //    })
        //});

        $(function () {
            $('#upload-logo').click(function (e) {
                $('#file-input').click();
            });
            $('#file-input').change(sendFile);
        });


        function sendFile() {
            var formData = new FormData();
            formData.append('file', $('#file-input')[0].files[0]);
            $.ajax({
                type: 'post',
                url: 'File/UploadProfileImage?personId=@Model.PersonId',
                data: formData,
                success: function (response) {
                    $("#image-profile").attr("src", response.additionalData.src);
                },
                processData: false,
                contentType: false,
                error: function () {
                    alert("Whoops something went wrong!");
                }
            });
        }

        $(function () {
            $("#save-person-submit").click(function (e) {
                var valdata = $("#SavePerson :input").serialize();
                $.ajax({
                    url: "/Person/EditStaffGeneralInformation",
                    type: "POST",
                    dataType: 'json',
                    data: valdata
                }).done(function (response) {
                    $.toast({
                        heading: response.header,
                        text: response.message,
                        position: 'bottom-right',
                        loaderBg: response.color,
                        icon: response.icon,
                        hideAfter: 10000
                    });
                    $("#person-full-name").html(response.additionalData.fullName);
                    //$("#person-address").html(response.additionalData.address);
                    $("#person-date").html(response.additionalData.normalizedDateOfBirth);
                });
            });
        })
    });
</script>

Kiddywee/Views/Person/Index.cshtml
@model List<PersonViewModel>
@{
    Layout = null;
}
<div class="row">
    @foreach (PersonViewModel item in Model)
    {

        <div class="col-md-3 el-element-overlay person-card @item.PersonRoleCssClassNoStyles" data-name="@item.FullName">
            <div class="el-card-item">
                <div class="card card-body el-overlay-1 @item.AttendanceCssClass @item.PersonRoleCssClass">
                    <div class="row">
                        <div class="col-md-5 text-center">
                            <img src="@Url.Action("GetProfileImage", "File", new { personId = item.Id})" style="width:85px;height:85px;" alt="user" class="img-circle img-responsive">
                        </div>
                        <div class="col-md-7">
                            <h3 class="box-title m-b-0">@item.FirstName<br />@item.LastName</h3>
                        </div>
                        <div class="el-overlay">
                            <ul class="el-info">
                                <li><a class="btn default btn-outline edit-person" data-url="@Url.Action(item.EditAction, "Person", new { personId = item.Id })"><i class="sl-icon-user"></i></a></li>
                                @if (item.CheckOutTime.HasValue == false)
                                {
                                    <li>
                                        <a class="btn default btn-outline checkInOut-person" data-classid="@item.ClassId" data-url="@Url.Action("CheckInOut", "Attendance", new { personId = item.Id, classId = item.ClassId })">
                                            @Html.Raw(item.CheckInOutIcon)
                                        </a>
                                    </li>
                                }

                                <li><a class="btn default btn-outline" data-url=""><i class="sl-icon-note"></i></a></li>
                                <li><a class="btn default btn-outline"><i class="sl-icon-shield"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>